from functions.git import *
from functions.common import *
from functions.variables import *
from functions.email import *

# Sender of the mail
SENDER = 'KubeBot'
# Subject of the mail
SUBJECT = 'License expiration is comming!'

# List of mail recipients
RECIPIENTS_LIST = [
'change_me@kube.local',
]

# List for licenses that will expire soon
licenses = []

# vEPC nodes
licenses.extend(expired_licenses(vepc, vepcs, USERNAME, PASSWORD))

# To create mail HTML body open the file containing 
# nodes with expiring license in HTML format
# This file is output from validate_license() function
with open(TMP_PATH + 'body_table.txt', 'r') as f:
	body_table = f.read()

# Body of the email message in HTML format
BODY = """\
<!DOCTYPE html>
<html>
<head><title></title>
</head>
<style type="text/css">
body {font-family: Calibri !important; font-size: 15;}
table, td, tr {font-family: Calibri; font-size: 13; text-align:left;}
th {font-family: Calibri; font-size: 13; text-align:left; border-bottom: 1px solid #ff0000}
</style>
<body>
	Dear EPC,<br><br>Brace yourselves! The following licenses will expire soon!<br><br>
	<table style="width:500px">
		<tr><th>Node</th><th>Expire Date</th><th>Days left</th></tr>%s</table><br><br>
		Current licenses are attached to this mail<br><br>
		You know nothing!<br>Your Python

</body>
</html>
""" % (body_table)

# Send email
print('Sending email')
send_email(SENDER, RECIPIENTS_LIST, SUBJECT, BODY, licenses)
# Clear temporary files generated by the script
print('Clearing files temporary created by script')
clear_temporary_files(LICENSE_EXTENSION)